version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ***-east-*)
      - REPOSITORY_URI=334240579318.dkr.ecr.us-east-1.amazonaws.com/ecs-cicd-nginx
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 334240579318.dkr.ecr.us-east-1.amazonaws.com/ecs-cicd-nginx:latest .
      - docker tag 334240579318.dkr.ecr.us-east-1.amazonaws.com/ecs-cicd-nginx:latest 334240579318.dkr.ecr.us-east-1.amazonaws.com/ecs-cicd-nginx:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker images...
      - docker push 334240579318.dkr.ecr.us-east-1.amazonaws.com/ecs-cicd-nginx:latest
      - docker push 334240579318.dkr.ecr.us-east-1.amazonaws.com/ecs-cicd-nginx:$IMAGE_TAG
      - echo Writing definitions file...
      - printf '[{"name":"project-container","imageUri":"%s"}]' 334240579318.dkr.ecr.us-east-1.amazonaws.com/ecs-cicd-nginx:$IMAGE_TAG > taskdefinition.json
artifacts:
    files: taskdefinition.json
